export function isZh() {
  if (typeof TranslationLanguage === 'string' && TranslationLanguage) {
    const language = TranslationLanguage.toLowerCase();
    return language === 'cn' || language === 'tw';
  }
  return (navigator.language || '').toLowerCase().startsWith('zh');
}

const LANG = {
  zh: {
    tabEdit: '編輯',
    tabOpacity: '透明度',
    tabLayers: '圖層',
    tabSettings: '設定',
    secPart: '部件',
    allParts: '整件衣服',
    opacity: '透明度',
    coord: '座標',
    coordDrag: '拖移',
    rotate: '旋轉',
    rotateDrag: '拖移',
    scale: '縮放',
    scaleDrag: '拖移',
    skew: '傾斜',
    mirror: '鏡射',
    mirrorH: '水平',
    mirrorV: '垂直',
    mirrorCopy: '水平複製',
    mirrorCopyV: '垂直複製',
    mirrorCenter: '鏡射',
    rotHint: '拖動把手旋轉',
    colorPickerTitle: '選色器',
    colorPickerConfirm: '確認',
    colorPickerCancel: '取消',
    harmSec: '和諧色',
    shadesSec: '漸層',
    savedSec: '已儲存',
    harmCompl: '互補',
    harmTriadic: '三角',
    harmAnalog: '類比',
    harmSplit: '分裂',
    harmTetr: '四角',
    colorSave: '儲存',
    colorClear: '清除',
    layerPriority: '優先度',
    noLayers: '此物品無可編輯圖層',
    settingsEmpty: '設定\n功能擴充中',
    viewControl: '視圖控制',
    offset: '位移',
    background: '背景',
    pose: 'POSE',
    hide: '隱藏',
    fullbody: '全身',
    closeup: '特寫',
    solid: '素色',
    grid: '格線',
    image: '圖片',
    setting: '設定',
  },
  en: {
    tabEdit: 'Edit',
    tabOpacity: 'Opacity',
    tabLayers: 'Layers',
    tabSettings: 'Settings',
    secPart: 'Layers',
    allParts: 'Whole Item',
    opacity: 'Opacity',
    coord: 'Position',
    coordDrag: 'Drag',
    rotate: 'Rotation',
    rotateDrag: 'Drag',
    scale: 'Scale',
    scaleDrag: 'Drag',
    skew: 'Skew',
    mirror: 'Mirror',
    mirrorH: 'Horiz.',
    mirrorV: 'Vert.',
    mirrorCopy: 'Copy H',
    mirrorCopyV: 'Copy V',
    mirrorCenter: 'Axis',
    rotHint: 'Drag handle to rotate',
    colorPickerTitle: 'Color Picker',
    colorPickerConfirm: 'Confirm',
    colorPickerCancel: 'Cancel',
    harmSec: 'Harmony',
    shadesSec: 'Shades',
    savedSec: 'Saved',
    harmCompl: 'Compl.',
    harmTriadic: 'Triadic',
    harmAnalog: 'Analog.',
    harmSplit: 'Split',
    harmTetr: 'Tetr.',
    colorSave: 'Save',
    colorClear: 'Clear',
    layerPriority: 'Priority',
    noLayers: 'No editable layers',
    settingsEmpty: 'Settings\nMore features coming soon',
    viewControl: 'View Control',
    offset: 'Offset',
    background: 'BG',
    pose: 'POSE',
    hide: 'Hide',
    fullbody: 'Full',
    closeup: 'Close',
    solid: 'Solid',
    grid: 'Grid',
    image: 'Image',
    setting: 'Setting',
  },
} as const;

export type LangKey = keyof typeof LANG.en;

export function t(key: LangKey) {
  return (isZh() ? LANG.zh : LANG.en)[key] ?? key;
}
